GET http://localhost:3001/api/notes

###
POST http://localhost:3001/api/notes 
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0ZDgwNDNhYzU3ZDg0ZDg5ZjZiYzc3NyIsImlhdCI6MTY5MTkzODEzN30.imJznyNWy1hDpp0SHBD6hGAX5gd63h84undg-LNMZIk

{
    "content": "Postman hoće da zeza",
    "important": true
}

###
PUT http://localhost:3001/api/notes/64caade93d32dd04e1ed0dd2
Content-Type: application/json

{
    "content": "JavaScript is strange",
    "important": false

}